"""
Celery worker for NeuCast — runs heavy prediction tasks in background.
"""
import os
import json
import logging
import numpy as np
import pandas as pd

from celery import Celery
from celery.signals import worker_ready

from app.prediction import run_prediction, fetch_and_preprocess

logger = logging.getLogger(__name__)

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6380/0")

celery_app = Celery("neucast", broker=REDIS_URL, backend=REDIS_URL)
celery_app.conf.update(
    task_serializer="pickle",
    result_serializer="pickle",
    accept_content=["pickle", "json"],
    task_track_started=True,
    result_expires=3600,
    worker_max_tasks_per_child=50,
    worker_concurrency=2,
    task_soft_time_limit=300,
    task_time_limit=360,
)


@worker_ready.connect
def _warmup_tcn_on_worker_ready(**_kwargs):
    """Preload TCN base model at worker startup so the first prediction
    task doesn't pay the ~3-4s model-load cost on a cold worker.

    The base model is process-global (cached via _get_model in prediction.py)
    so this runs once per forked child when max_tasks_per_child recycles.
    """
    try:
        from app.prediction import _get_model
        import time
        t0 = time.time()
        _get_model()
        logger.info(f"TCN base model warmup completed in {time.time() - t0:.2f}s")
    except Exception as e:
        logger.warning(f"TCN warmup failed: {e}")


def _generate_mini_pdf(ticker: str, result: dict) -> bytes | None:
    """Generate a compact PDF summary for Telegram."""
    try:
        from fpdf import FPDF
        import io

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Header
        pdf.set_fill_color(10, 14, 23)
        pdf.rect(0, 0, 210, 40, "F")
        pdf.set_fill_color(16, 185, 129)
        pdf.rect(0, 38, 210, 2, "F")
        pdf.set_xy(15, 8)
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 10, f"NeuCast — {ticker}")
        pdf.set_xy(15, 22)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(0, 8, f"Model: {result.get('model_name', 'Ensemble')}")

        pdf.set_y(48)
        pdf.set_text_color(30, 41, 59)

        # Metrics
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Model Accuracy (Test Set)", ln=True)
        pdf.set_font("Helvetica", "", 10)
        metrics = [
            ("MAPE", f"{result['mape']:.2f}%"),
            ("MAE", f"${result['mae']:.2f}"),
            ("RMSE", f"${result['rmse']:.2f}"),
            ("R²", f"{result['r2']:.4f}"),
            ("Direction Accuracy", f"{result['dir_acc']:.1f}%"),
        ]
        for name, val in metrics:
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(80, 7, f"  {name}:")
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, val, ln=True)

        # Backtest
        bt = result.get("backtest")
        if bt:
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 10, "Backtesting", ln=True)
            pdf.set_font("Helvetica", "", 10)
            bt_metrics = [
                ("Strategy Return", f"{bt['total_return']:+.2f}%"),
                ("Buy & Hold Return", f"{bt['bnh_return']:+.2f}%"),
                ("Alpha", f"{bt['total_return'] - bt['bnh_return']:+.2f}%"),
                ("Sharpe Ratio", f"{bt['sharpe']}"),
                ("Max Drawdown", f"{bt['max_drawdown']}%"),
                ("Win Rate", f"{bt['win_rate']}%"),
                ("Profit Factor", f"{bt['profit_factor']}"),
            ]
            for name, val in bt_metrics:
                pdf.set_font("Helvetica", "", 10)
                pdf.cell(80, 7, f"  {name}:")
                pdf.set_font("Helvetica", "B", 10)
                pdf.cell(0, 7, val, ln=True)

        # Per-model metrics
        mm = result.get("model_metrics")
        if mm:
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 10, "Per-Model Metrics", ln=True)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_fill_color(241, 245, 249)
            pdf.cell(45, 7, "Model", 1, 0, "C", True)
            pdf.cell(30, 7, "MAE ($)", 1, 0, "C", True)
            pdf.cell(30, 7, "RMSE ($)", 1, 0, "C", True)
            pdf.cell(30, 7, "MAPE (%)", 1, 0, "C", True)
            pdf.cell(30, 7, "R²", 1, 1, "C", True)
            pdf.set_font("Helvetica", "", 9)
            for name, m in mm.items():
                pdf.cell(45, 6, name, 1, 0)
                pdf.cell(30, 6, str(m["mae"]), 1, 0, "C")
                pdf.cell(30, 6, str(m["rmse"]), 1, 0, "C")
                pdf.cell(30, 6, f"{m['mape']}%", 1, 0, "C")
                pdf.cell(30, 6, str(m["r2"]), 1, 1, "C")

        # Footer
        pdf.ln(8)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(0, 5, "Generated by NeuCast AI — neucast.ru", 0, 0, "C")

        buf = io.BytesIO()
        pdf.output(buf)
        return buf.getvalue()
    except Exception as e:
        logger.warning(f"Failed to generate PDF: {e}")
        return None


def _send_telegram_notification(user_id: int, ticker: str, result: dict, task_id: str = None):
    """Send Telegram notification with prediction summary + PDF."""
    try:
        from app.telegram_bot import is_configured, is_linked, send_prediction_result

        if not is_configured() or not is_linked(user_id):
            logger.info(f"Telegram skip: configured={is_configured()}, linked={is_linked(user_id)}")
            return

        pdf_bytes = _generate_mini_pdf(ticker, result)
        logger.info(f"PDF generated: {len(pdf_bytes) if pdf_bytes else 0} bytes")

        send_prediction_result(
            user_id=user_id,
            ticker=ticker,
            task_id=task_id,
            pdf_bytes=pdf_bytes,
            mae=f"{result['mae']:.2f}",
            mape=f"{result['mape']:.2f}",
            r2=f"{result['r2']:.4f}",
            dir_acc=f"{result['dir_acc']:.1f}",
            model_name=result.get("model_name", "Ensemble"),
        )
        logger.info(f"Telegram notification sent to user {user_id} for {ticker}")
    except Exception as e:
        logger.warning(f"Failed to send Telegram notification: {e}", exc_info=True)


@celery_app.task(bind=True, name="neucast.predict")
def run_prediction_task(self, ticker: str, start_date: str, end_date: str,
                        days_ahead: int, user_id: int = None):
    """Heavy prediction task — runs in Celery worker process."""
    self.update_state(state="FETCHING", meta={"status": "Загрузка данных с Yahoo Finance..."})

    try:
        df = fetch_and_preprocess(ticker, start_date, end_date)
    except ValueError as e:
        return {"error": str(e)}

    self.update_state(state="PREDICTING", meta={"status": "Расчёт прогноза (TCN + Ensemble)..."})

    result = run_prediction(df, days_ahead)

    # Send Telegram notification
    if user_id:
        _send_telegram_notification(user_id, ticker, result, task_id=self.request.id)

    # Convert numpy arrays to lists for serialization
    serializable = {}
    for k, v in result.items():
        if isinstance(v, np.ndarray):
            serializable[k] = v.tolist()
        elif isinstance(v, pd.DatetimeIndex):
            serializable[k] = v.strftime("%Y-%m-%d").tolist()
        else:
            serializable[k] = v

    serializable["_df_json"] = df.to_json(date_format="iso")
    serializable["ticker"] = ticker
    serializable["start_date"] = start_date
    serializable["end_date"] = end_date
    serializable["days_ahead"] = days_ahead

    return serializable
